# Generated by Django 5.2.6 on 2025-10-09 01:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('SUCURSAL', 'Sucursal'), ('TRANSITO', 'Tránsito')], default='PRINCIPAL', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'db_table': 'bodegas',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=50, unique=True)),
                ('fecha_produccion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Obligatorio si producto.perishable = true', null=True)),
                ('cantidad_inicial', models.DecimalField(decimal_places=6, max_digits=18)),
                ('cantidad_disponible', models.DecimalField(decimal_places=6, help_text='Debe ser <= cantidad_inicial', max_digits=18)),
                ('cantidad_reservada', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=6, help_text='Costo unitario del lote', max_digits=18, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('VENCIDO', 'Vencido'), ('AGOTADO', 'Agotado'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', max_length=10)),
                ('motivo_bloqueo', models.TextField(blank=True, help_text='Razón del bloqueo si estado = BLOQUEADO', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='maestros.producto')),
                ('proveedor', models.ForeignKey(blank=True, help_text='Proveedor del lote', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='maestros.proveedor')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'db_table': 'lotes',
            },
        ),
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('BAJO_STOCK', 'Bajo Stock'), ('SOBRE_STOCK', 'Sobre Stock'), ('POR_VENCER', 'Por Vencer'), ('VENCIDO', 'Vencido'), ('SIN_STOCK', 'Sin Stock')], max_length=15)),
                ('cantidad_actual', models.DecimalField(decimal_places=6, max_digits=18)),
                ('cantidad_limite', models.DecimalField(blank=True, decimal_places=6, help_text='Stock mínimo/máximo según tipo de alerta', max_digits=18, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Obligatorio para POR_VENCER, VENCIDO', null=True)),
                ('dias_vencimiento', models.IntegerField(blank=True, help_text='Días hasta vencimiento para POR_VENCER', null=True)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=8)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('RESUELTA', 'Resuelta'), ('IGNORADA', 'Ignorada')], default='ACTIVA', max_length=10)),
                ('fecha_generacion', models.DateTimeField()),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('motivo_resolucion', models.TextField(blank=True, help_text='Explicación de cómo se resolvió', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='maestros.producto')),
                ('resuelto_por_usuario', models.ForeignKey(blank=True, help_text='Usuario que marcó como resuelta', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertas_resueltas', to=settings.AUTH_USER_MODEL)),
                ('bodega', models.ForeignKey(blank=True, help_text='Obligatorio para BAJO_STOCK, SOBRE_STOCK, SIN_STOCK', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventario.bodega')),
                ('lote', models.ForeignKey(blank=True, help_text='Obligatorio para POR_VENCER, VENCIDO', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventario.lote')),
            ],
            options={
                'verbose_name': 'Alerta de Stock',
                'verbose_name_plural': 'Alertas de Stock',
                'db_table': 'alertas_stock',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('INGRESO', 'Ingreso'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('DEVOLUCION', 'Devolución'), ('TRANSFERENCIA', 'Transferencia')], max_length=15)),
                ('fecha_movimiento', models.DateTimeField()),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=18)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('serie', models.CharField(blank=True, help_text='Obligatorio si producto.control_por_serie = true', max_length=100, null=True)),
                ('documento_padre_tipo', models.CharField(blank=True, choices=[('ORDEN_COMPRA', 'Orden de Compra'), ('ORDEN_VENTA', 'Orden de Venta'), ('AJUSTE_MANUAL', 'Ajuste Manual'), ('TRANSFERENCIA_INTERNA', 'Transferencia Interna'), ('DEVOLUCION_CLIENTE', 'Devolución Cliente'), ('DEVOLUCION_PROVEEDOR', 'Devolución Proveedor')], max_length=25, null=True)),
                ('documento_padre_id', models.IntegerField(blank=True, help_text='ID del documento que origina el movimiento', null=True)),
                ('documento_referencia', models.CharField(blank=True, help_text='Factura, guía despacho, etc', max_length=50, null=True)),
                ('motivo_ajuste', models.TextField(blank=True, help_text='Obligatorio para AJUSTE y DEVOLUCION', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=10)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, help_text='Fecha de confirmación del movimiento', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bodega_destino', models.ForeignKey(blank=True, help_text='Obligatorio para INGRESO y TRANSFERENCIA', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_ingreso', to='inventario.bodega')),
                ('bodega_origen', models.ForeignKey(blank=True, help_text='Obligatorio para SALIDA, AJUSTE y TRANSFERENCIA', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_salida', to='inventario.bodega')),
                ('lote', models.ForeignKey(blank=True, help_text='Obligatorio si producto.control_por_lote = true', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='maestros.producto')),
                ('proveedor', models.ForeignKey(blank=True, help_text='Obligatorio para INGRESO y DEVOLUCION', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='maestros.proveedor')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='maestros.unidadmedida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to=settings.AUTH_USER_MODEL)),
                ('usuario_confirmacion', models.ForeignKey(blank=True, help_text='Usuario que confirmó el movimiento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_confirmados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'movimientos_inventario',
            },
        ),
        migrations.CreateModel(
            name='StockActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('cantidad_reservada', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('cantidad_transito', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('ultimo_ingreso', models.DateTimeField(blank=True, null=True)),
                ('ultima_salida', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventario.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='maestros.producto')),
            ],
            options={
                'verbose_name': 'Stock Actual',
                'verbose_name_plural': 'Stocks Actuales',
                'db_table': 'stock_actual',
            },
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['codigo_lote'], name='lotes_codigo__211d52_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['producto'], name='lotes_product_fd9590_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['fecha_vencimiento'], name='lotes_fecha_v_ce4cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['estado'], name='lotes_estado_a6768b_idx'),
        ),
        migrations.AddIndex(
            model_name='alertastock',
            index=models.Index(fields=['producto'], name='alertas_sto_product_d45301_idx'),
        ),
        migrations.AddIndex(
            model_name='alertastock',
            index=models.Index(fields=['tipo_alerta'], name='alertas_sto_tipo_al_b5f8ac_idx'),
        ),
        migrations.AddIndex(
            model_name='alertastock',
            index=models.Index(fields=['estado'], name='alertas_sto_estado_ff48e6_idx'),
        ),
        migrations.AddIndex(
            model_name='alertastock',
            index=models.Index(fields=['fecha_generacion'], name='alertas_sto_fecha_g_257108_idx'),
        ),
        migrations.AddIndex(
            model_name='alertastock',
            index=models.Index(fields=['bodega'], name='alertas_sto_bodega__c53c35_idx'),
        ),
        migrations.AddIndex(
            model_name='alertastock',
            index=models.Index(fields=['lote'], name='alertas_sto_lote_id_7a2be0_idx'),
        ),
        migrations.AddIndex(
            model_name='alertastock',
            index=models.Index(fields=['prioridad'], name='alertas_sto_priorid_5cf121_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo_movimiento'], name='movimientos_tipo_mo_a03876_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['fecha_movimiento'], name='movimientos_fecha_m_c279a0_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['producto'], name='movimientos_product_3deae0_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['bodega_origen'], name='movimientos_bodega__e32703_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['bodega_destino'], name='movimientos_bodega__29ba2d_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['estado'], name='movimientos_estado_e517b7_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['documento_padre_tipo'], name='movimientos_documen_4dd075_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['lote'], name='movimientos_lote_id_069a3d_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['unidad_medida'], name='movimientos_unidad__c6f169_idx'),
        ),
        migrations.AddIndex(
            model_name='stockactual',
            index=models.Index(fields=['producto'], name='stock_actua_product_ceb510_idx'),
        ),
        migrations.AddIndex(
            model_name='stockactual',
            index=models.Index(fields=['bodega'], name='stock_actua_bodega__c267d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockactual',
            unique_together={('producto', 'bodega')},
        ),
    ]
