# Generated by Django 5.2.7 on 2025-10-25 01:03

import catalogo.models
import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del catálogo (ej: CAT-2024-001)', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El código solo puede contener letras mayúsculas, números y guiones', regex='^[A-Z0-9-]+$')])),
                ('nombre', models.CharField(help_text='Nombre del catálogo', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del catálogo', null=True)),
                ('tipo', models.CharField(choices=[('FISICO', 'Físico'), ('DIGITAL', 'Digital'), ('SERVICIO', 'Servicio')], default='FISICO', max_length=10)),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio base del producto', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('descuento', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento (0-100)', max_digits=5, validators=[catalogo.models.validar_descuento])),
                ('stock_disponible', models.IntegerField(default=0, help_text='Cantidad disponible en stock', validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_minimo', models.IntegerField(default=5, help_text='Stock mínimo requerido', validators=[django.core.validators.MinValueValidator(0)])),
                ('calificacion', models.DecimalField(decimal_places=2, default=0, help_text='Calificación del producto (0-5)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('imagen_url', models.URLField(blank=True, help_text='URL de la imagen del producto', max_length=500, null=True, validators=[catalogo.models.validar_imagen_url])),
                ('contacto', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Número de teléfono debe estar en formato: +999999999. Hasta 15 dígitos.', regex='^\\+?1?\\d{9,15}$')])),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=10)),
                ('destacado', models.BooleanField(default=False, help_text='Marcar como producto destacado')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de inicio de publicación')),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Fecha de fin de publicación', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catálogo',
                'verbose_name_plural': 'Catálogos',
                'db_table': 'catalogo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['codigo'], name='catalogo_codigo_350c97_idx'), models.Index(fields=['estado'], name='catalogo_estado_5a6bad_idx'), models.Index(fields=['destacado'], name='catalogo_destaca_485b38_idx')],
            },
        ),
    ]
