# Generated by Django 5.2.7 on 2025-10-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='idx_reset_token',
            old_name='password_re_token_060a1f_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='idx_reset_user',
            old_name='password_re_usuario_6c2c21_idx',
        ),
        migrations.RenameIndex(
            model_name='sesion',
            new_name='idx_sesion_token',
            old_name='sesiones_token_s_9b7845_idx',
        ),
        migrations.RenameIndex(
            model_name='sesion',
            new_name='idx_sesion_user',
            old_name='sesiones_usuario_710990_idx',
        ),
        migrations.RenameIndex(
            model_name='usuario',
            new_name='idx_username',
            old_name='usuarios_usernam_7abab6_idx',
        ),
        migrations.RenameIndex(
            model_name='usuario',
            new_name='idx_email',
            old_name='usuarios_email_0ff7b3_idx',
        ),
        migrations.RenameIndex(
            model_name='usuario',
            new_name='idx_estado',
            old_name='usuarios_estado_7877c9_idx',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
