# Generated by Django 5.2.7 on 2025-10-12 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_rename_password_re_token_060a1f_idx_idx_reset_token_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='passwordresettoken',
            name='idx_reset_token',
        ),
        migrations.RemoveIndex(
            model_name='passwordresettoken',
            name='idx_reset_user',
        ),
        migrations.RemoveIndex(
            model_name='sesion',
            name='idx_sesion_token',
        ),
        migrations.RemoveIndex(
            model_name='sesion',
            name='idx_sesion_user',
        ),
        migrations.RemoveIndex(
            model_name='usuario',
            name='idx_username',
        ),
        migrations.RemoveIndex(
            model_name='usuario',
            name='idx_email',
        ),
        migrations.RemoveIndex(
            model_name='usuario',
            name='idx_estado',
        ),
    ]
