# Generated by Django 5.2.7 on 2025-11-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_remove_passwordresettoken_idx_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Imagen de perfil (máximo 2MB, formatos: JPG, PNG, WEBP)', null=True, upload_to='avatars/'),
        ),
    ]
