# Generated by Django 5.2.7 on 2025-11-04 00:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_usuario_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordChangeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('expira_en', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_change_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_change_codes',
                'indexes': [models.Index(fields=['codigo', 'usado', 'expira_en'], name='idx_codigo_activo')],
            },
        ),
    ]
