# Generated by Django 5.2.8 on 2025-11-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0005_passwordchangecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bloqueado_hasta',
            field=models.DateTimeField(blank=True, help_text='Fecha hasta la cual la cuenta está bloqueada', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='intentos_fallidos',
            field=models.IntegerField(default=0, help_text='Contador de intentos fallidos de login'),
        ),
    ]
