# Generated by Django 5.2.8 on 2025-11-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0006_usuario_bloqueado_hasta_usuario_intentos_fallidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False, help_text='Si el usuario debe cambiar su contraseña en el próximo login'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_password_temporal',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se asignó la contraseña temporal', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password_es_temporal',
            field=models.BooleanField(default=False, help_text='Indica si la contraseña actual es temporal (generada por el sistema)'),
        ),
    ]
