# Generated by Django 5.2.7 on 2025-10-10 06:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_nif', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('PERSONA', 'Persona Natural'), ('EMPRESA', 'Empresa')], default='PERSONA', max_length=10)),
                ('nombre', models.CharField(help_text='Nombre completo o razón social', max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'indexes': [models.Index(fields=['rut_nif'], name='clientes_rut_nif_6f36aa_idx'), models.Index(fields=['nombre'], name='clientes_nombre_4aa028_idx')],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_venta', models.CharField(max_length=50, unique=True)),
                ('cliente_anonimo', models.CharField(blank=True, help_text='Nombre del cliente sin registro', max_length=150, null=True)),
                ('fecha_venta', models.DateField(default=django.utils.timezone.now)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('EN_PREPARACION', 'En Preparación'), ('LISTA', 'Lista para Entrega'), ('ENTREGADA', 'Entregada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('forma_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('CREDITO', 'Crédito')], default='EFECTIVO', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('moneda', models.CharField(default='CLP', max_length=8)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente opcional', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='ventas.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=18)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=18)),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_detalle', to='maestros.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
                'db_table': 'ventas_detalle',
            },
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['numero_venta'], name='ventas_numero__d43a36_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['cliente'], name='ventas_cliente_b73e43_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['vendedor'], name='ventas_vendedo_1a3878_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado'], name='ventas_estado_505824_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha_venta'], name='ventas_fecha_v_df623b_idx'),
        ),
        migrations.AddIndex(
            model_name='ventadetalle',
            index=models.Index(fields=['venta'], name='ventas_deta_venta_i_431a94_idx'),
        ),
        migrations.AddIndex(
            model_name='ventadetalle',
            index=models.Index(fields=['producto'], name='ventas_deta_product_c74ea2_idx'),
        ),
    ]
