# Generated by Django 5.2.6 on 2025-10-09 01:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marcas',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria_padre', models.ForeignKey(blank=True, help_text='Para subcategorías', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='maestros.categoria')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_nif', models.CharField(help_text='RUT o NIF único', max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('nombre_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=128, null=True)),
                ('pais', models.CharField(default='Chile', max_length=64)),
                ('condiciones_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('30_DIAS', '30 días'), ('60_DIAS', '60 días'), ('90_DIAS', '90 días'), ('OTRO', 'Otro')], max_length=10)),
                ('condiciones_pago_detalle', models.CharField(blank=True, help_text='Detalle si es OTRO', max_length=255, null=True)),
                ('moneda', models.CharField(default='CLP', help_text='Código ISO moneda', max_length=8)),
                ('contacto_principal_nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('contacto_principal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacto_principal_telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'indexes': [models.Index(fields=['rut_nif'], name='proveedores_rut_nif_5ef129_idx'), models.Index(fields=['razon_social'], name='proveedores_razon_s_2d0255_idx'), models.Index(fields=['estado'], name='proveedores_estado_e45323_idx')],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la unidad (ej: KG, L, UND)', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Nombre completo de la unidad', max_length=50)),
                ('tipo', models.CharField(choices=[('PESO', 'Peso'), ('VOLUMEN', 'Volumen'), ('LONGITUD', 'Longitud'), ('UNIDAD', 'Unidad'), ('TIEMPO', 'Tiempo')], max_length=10)),
                ('factor_base', models.DecimalField(decimal_places=6, default=1, help_text='Factor de conversión a unidad base del tipo', max_digits=18)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'unidades_medida',
                'indexes': [models.Index(fields=['codigo'], name='unidades_me_codigo_8dd584_idx'), models.Index(fields=['tipo'], name='unidades_me_tipo_6f70c3_idx'), models.Index(fields=['activo'], name='unidades_me_activo_995d1c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Código SKU único', max_length=50, unique=True)),
                ('ean_upc', models.CharField(blank=True, help_text='Código de barras EAN/UPC', max_length=20, null=True, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('factor_conversion', models.DecimalField(decimal_places=4, default=1, help_text='Factor conversión compra/venta', max_digits=10)),
                ('costo_estandar', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('costo_promedio', models.DecimalField(blank=True, decimal_places=6, help_text='Calculado automáticamente', max_digits=18, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('impuesto_iva', models.DecimalField(decimal_places=2, default=19, help_text='Porcentaje IVA', max_digits=5)),
                ('stock_minimo', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('stock_maximo', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('punto_reorden', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('perishable', models.BooleanField(default=False, help_text='Es perecedero')),
                ('control_por_lote', models.BooleanField(default=False)),
                ('control_por_serie', models.BooleanField(default=False)),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
                ('ficha_tecnica_url', models.URLField(blank=True, max_length=500, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('DESCONTINUADO', 'Descontinuado')], default='ACTIVO', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='maestros.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='maestros.marca')),
                ('uom_compra', models.ForeignKey(help_text='Unidad de medida para compra', on_delete=django.db.models.deletion.PROTECT, related_name='productos_compra', to='maestros.unidadmedida')),
                ('uom_stock', models.ForeignKey(help_text='Unidad de medida para inventario', on_delete=django.db.models.deletion.PROTECT, related_name='productos_stock', to='maestros.unidadmedida')),
                ('uom_venta', models.ForeignKey(help_text='Unidad de medida para venta', on_delete=django.db.models.deletion.PROTECT, related_name='productos_venta', to='maestros.unidadmedida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=6, help_text='Costo del producto con este proveedor', max_digits=18)),
                ('lead_time_dias', models.IntegerField(default=7, help_text='Tiempo de entrega en días')),
                ('min_lote', models.DecimalField(decimal_places=6, default=1, help_text='Cantidad mínima de compra', max_digits=18)),
                ('descuento_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de descuento', max_digits=5, null=True)),
                ('preferente', models.BooleanField(default=False, help_text='Proveedor preferente')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='maestros.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='maestros.proveedor')),
            ],
            options={
                'verbose_name': 'Producto-Proveedor',
                'verbose_name_plural': 'Productos-Proveedores',
                'db_table': 'productos_proveedores',
                'indexes': [models.Index(fields=['producto'], name='productos_p_product_06bc4f_idx'), models.Index(fields=['proveedor'], name='productos_p_proveed_581a5c_idx'), models.Index(fields=['preferente'], name='productos_p_prefere_eb83fe_idx')],
                'unique_together': {('producto', 'proveedor')},
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['sku'], name='productos_sku_a62667_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='productos_nombre_d31432_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria'], name='productos_categor_169a62_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['estado'], name='productos_estado_184900_idx'),
        ),
    ]
