# Generated by Django 5.2.7 on 2025-10-12 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='producto',
            name='productos_nombre_d31432_idx',
        ),
        migrations.RemoveIndex(
            model_name='proveedor',
            name='proveedores_razon_s_2d0255_idx',
        ),
    ]
