# Generated by Django 5.2.7 on 2025-11-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_remove_producto_productos_nombre_d31432_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del producto (JPG, PNG, máx 5MB)', null=True, upload_to='productos/'),
        ),
    ]
