# Generated by Django 4.2.25 on 2025-11-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='dias_vencimiento',
            field=models.IntegerField(blank=True, help_text='Días hasta vencimiento desde fecha de producción', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='meses_vencimiento',
            field=models.IntegerField(blank=True, help_text='Meses hasta vencimiento (alternativo a días)', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='requiere_fecha_vencimiento',
            field=models.BooleanField(default=False, help_text='Requiere control de fecha de vencimiento'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_actual',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Stock actual calculado automáticamente', max_digits=18),
        ),
    ]
