# Generated by Django 5.2.6 on 2025-10-09 01:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Clave de configuración única', max_length=100, unique=True)),
                ('valor', models.TextField(help_text='Valor de la configuración')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('STRING', 'String'), ('NUMBER', 'Number'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON'), ('DATE', 'Date')], max_length=10)),
                ('categoria', models.CharField(help_text='Categoría de la configuración', max_length=50)),
                ('editable', models.BooleanField(default=True, help_text='Si puede ser editado por usuarios')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'db_table': 'configuracion_sistema',
                'indexes': [models.Index(fields=['clave'], name='configuraci_clave_2555cf_idx'), models.Index(fields=['categoria'], name='configuraci_categor_1e5d8e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReglaNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('tabla_afectada', models.CharField(max_length=100)),
                ('tipo_regla', models.CharField(choices=[('VALIDACION', 'Validación'), ('CALCULO', 'Cálculo'), ('TRIGGER', 'Trigger'), ('CONSTRAINT', 'Constraint')], max_length=15)),
                ('condicion_sql', models.TextField(blank=True, help_text='Condición SQL para la regla', null=True)),
                ('accion_sql', models.TextField(blank=True, help_text='Acción a ejecutar cuando se cumple la condición', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('prioridad', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regla de Negocio',
                'verbose_name_plural': 'Reglas de Negocio',
                'db_table': 'reglas_negocio',
                'indexes': [models.Index(fields=['tabla_afectada'], name='reglas_nego_tabla_a_ab150e_idx'), models.Index(fields=['tipo_regla'], name='reglas_nego_tipo_re_ebf36a_idx'), models.Index(fields=['activo'], name='reglas_nego_activo_6003df_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla_afectada', models.CharField(max_length=100)),
                ('accion', models.CharField(choices=[('INSERT', 'Insert'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('registro_id', models.IntegerField()),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'db_table': 'auditoria_log',
                'indexes': [models.Index(fields=['tabla_afectada'], name='auditoria_l_tabla_a_3b14a4_idx'), models.Index(fields=['accion'], name='auditoria_l_accion_868eae_idx'), models.Index(fields=['usuario'], name='auditoria_l_usuario_57b6f3_idx'), models.Index(fields=['created_at'], name='auditoria_l_created_cd810c_idx')],
            },
        ),
    ]
