# Generated by Django 5.2.8 on 2025-11-28 01:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditorialog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Log de Auditoría', 'verbose_name_plural': 'Logs de Auditoría'},
        ),
        migrations.RemoveIndex(
            model_name='auditorialog',
            name='auditoria_l_created_cd810c_idx',
        ),
        migrations.AddField(
            model_name='auditorialog',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción adicional del evento', null=True),
        ),
        migrations.AddField(
            model_name='auditorialog',
            name='exitoso',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auditorialog',
            name='registro_repr',
            field=models.CharField(blank=True, help_text='Representación legible del registro', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auditorialog',
            name='usuario_nombre',
            field=models.CharField(blank=True, help_text='Nombre completo del usuario (guardado para historial)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='auditorialog',
            name='accion',
            field=models.CharField(choices=[('INSERT', 'Insert'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ACCESO_DENEGADO', 'Acceso Denegado'), ('CAMBIO_PASSWORD', 'Cambio de Contraseña')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditorialog',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='auditorialog',
            name='registro_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditorialog',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['-created_at'], name='auditoria_l_created_9595d9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['tabla_afectada', '-created_at'], name='auditoria_l_tabla_a_7047b5_idx'),
        ),
    ]
