# Generated by Django 4.2.25 on 2025-11-04 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_costo_estandar_producto_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='categoria_padre',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='bodega',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='usuario_autorizacion',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='ordencompradetalle',
            name='orden_compra',
        ),
        migrations.RemoveField(
            model_name='ordencompradetalle',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='ordencompradetalle',
            name='unidad_medida',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='uom_compra',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='uom_stock',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='uom_venta',
        ),
        migrations.RemoveField(
            model_name='productoproveedor',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='productoproveedor',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='Bodega',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Lote',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='OrdenCompra',
        ),
        migrations.DeleteModel(
            name='OrdenCompraDetalle',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='ProductoProveedor',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='UnidadMedida',
        ),
    ]
