# Generated by Django 5.2.6 on 2025-10-09 01:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=50, unique=True)),
                ('fecha_orden', models.DateField()),
                ('fecha_entrega_esperada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('CONFIRMADA', 'Confirmada'), ('RECIBIDA_PARCIAL', 'Recibida Parcial'), ('RECIBIDA_COMPLETA', 'Recibida Completa'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('moneda', models.CharField(default='CLP', max_length=8)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='maestros.proveedor')),
                ('usuario_autorizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'db_table': 'ordenes_compra',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=6, max_digits=18)),
                ('cantidad_recibida', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('precio_unitario', models.DecimalField(decimal_places=6, max_digits=18)),
                ('descuento_pct', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.ordencompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra_detalle', to='maestros.producto')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra_detalle', to='maestros.unidadmedida')),
            ],
            options={
                'verbose_name': 'Detalle Orden de Compra',
                'verbose_name_plural': 'Detalles Órdenes de Compra',
                'db_table': 'ordenes_compra_detalle',
            },
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['numero_orden'], name='ordenes_com_numero__72b9e6_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['proveedor'], name='ordenes_com_proveed_6d9c2b_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['estado'], name='ordenes_com_estado_8ac831_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['fecha_orden'], name='ordenes_com_fecha_o_6951ee_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompradetalle',
            index=models.Index(fields=['orden_compra'], name='ordenes_com_orden_c_33f8ea_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompradetalle',
            index=models.Index(fields=['producto'], name='ordenes_com_product_2cc5b4_idx'),
        ),
    ]
